[Details]
Icon = "icon.png"
Name = "Image Restoration Suite"
ID = "com.strauhmanis.advanced-image-processing"
Version = "2.0.0"
Build = 1

[Metadata]
Developer = "Ervins Strauhmanis"
Category = "Graphics"
Copyright = "© 2025 Ervins Strauhmanis"

[Migrations]
# Enable fyne.Do migration for v2.6+ thread safety
fyneDo = true