Website = "https://github.com/resoltico/image-restoration-suite"

[Details]
  Icon = "icon.png"
  Name = "Image Restoration Suite"
  ID = "com.imagerestoration.suite"
  Version = "1.0.0"
  Build = 1

[LinuxAndBSD]
  GenericName = "Image Processing Tool"
  Categories = ["Graphics", "Photography"]
  Comment = "Image restoration and processing suite for historical documents and illustrations."
  Keywords = ["image", "restoration", "processing", "opencv", "otsu", "lanczos"]